## PyTorch Tutorial 02 - Tensor Basics

In [ ]:
import torch

### Creating a Tensor

In [2]:
x = torch.empty(3) # creating an empty 1D tensor of size 3
print(x)

tensor([0., 0., 0.])


In [3]:
x = torch.empty(3,2) # creating an empty 2D tensor of size 3,2
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [4]:
x = torch.empty(3,2,2) # creating an empty 3D tensor of size 3,2,2 and so on
print(x)

# other commands torch.zeros, torch.ones

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [6]:
# We can also pass dtype
x = torch.ones(2,2, dtype=torch.float16)
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [7]:
x = torch.tensor([1,2,3]) # Create by passing actual elements
print(x)

tensor([1, 2, 3])


### Tensor Arithmetic

In [14]:
# Tensor operations

x = torch.rand(2,2)
y = torch.rand(2,2)
print(x,y)

tensor([[0.7554, 0.4764],
        [0.9499, 0.8678]]) tensor([[0.3738, 0.4323],
        [0.6558, 0.8988]])


In [15]:
# Element wise addition
print(x+y) # Multiple ways to perform arithmetic operation on tensors
torch.add(x,y) 
print(y)
y.add_(x) # Trailing underscore performs inplace operations in Torch
# Without trailing underscore it will perform without inplace

print(y)

tensor([[1.1291, 0.9087],
        [1.6057, 1.7666]])
tensor([[0.3738, 0.4323],
        [0.6558, 0.8988]])
tensor([[1.1291, 0.9087],
        [1.6057, 1.7666]])


In [19]:
# same thing for sub, mul
y.sub_(x)
torch.sub(x,y)
print(x-y) # etc

print(y.mul(x))
print(y)

tensor([[2.6478, 1.4731],
        [3.1438, 2.5724]])
tensor([[-1.4295, -0.4748],
        [-2.0840, -1.4792]])
tensor([[-1.8924, -0.9967],
        [-2.1939, -1.7046]])


### Slicing Tensors

In [24]:
# Slicing operations on Tensors
x = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [25]:
print(x[:,0]) # All rows first column

tensor([1, 5, 9])


In [26]:
print(x[1,:]) # First row all columns

tensor([5, 6, 7, 8])


In [28]:
print(x[1,1]) # Specific value


6


In [31]:
x = torch.rand(4,4)
print(x)

# Using view to chang
y = x.view(-1,2) # Here Pytorch auto determines the correct size for "-1"
print(y)

tensor([[8.3812e-01, 3.5946e-01, 2.4022e-01, 8.0060e-01],
        [1.6612e-04, 5.1938e-01, 1.9210e-01, 5.4538e-01],
        [3.9348e-01, 3.7356e-01, 9.5387e-01, 2.7667e-01],
        [2.1563e-01, 1.5566e-01, 9.8775e-01, 9.7908e-01]])
tensor([[8.3812e-01, 3.5946e-01],
        [2.4022e-01, 8.0060e-01],
        [1.6612e-04, 5.1938e-01],
        [1.9210e-01, 5.4538e-01],
        [3.9348e-01, 3.7356e-01],
        [9.5387e-01, 2.7667e-01],
        [2.1563e-01, 1.5566e-01],
        [9.8775e-01, 9.7908e-01]])


In [36]:
# Converting tensor to numpy array
x = torch.ones(5)
y = x.numpy()
print(type(y),"\n",y)

# NOTE: If tensor is on cpu then both numpy array and tensor will have the same memory location

x += 1
print(y)

<class 'numpy.ndarray'> 
 [1. 1. 1. 1. 1.]


### CUDA

In [39]:
# no cuda in my Mac currently

if torch.cuda.is_available():
    device = torch.device("cuda")

    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)

    z = x+y
    print(z)
    z = z.to("cpu")

# numpy can only handle cpu tensors

In [41]:
torch.cuda.is_available()

False

In [44]:
# Requires gradient to be computed

torch.ones(5, requires_grad=True)

tensor([1., 1., 1., 1., 1.], requires_grad=True)